baseURL: https://yoursite.example.com/
footnoteReturnLinkContents: ↩
params:
  AuthorName: Jon Doe
  GitHubUser: spf13
  ListOfFoo:
  - foo1
  - foo2
  SidebarRecentLimit: 5
  Subtitle: Hugo is Absurdly Fast!
permalinks:
  posts: /:year/:month/:title/
title: Envoys of Dissonance
theme: "hugo-PaperMod"

params:
  profileMode:
    enabled: true
    title: "Envoys of Dissonance"
    subtitle: "Located on Aether DC, Gilgamesh"
    imageUrl: "<image Link>"
    imageTitle: "Envoys of Dissonance Logo"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: News
        url: "/news"
      - name: About
        url: "/about"
  
  socialIcons:
    - name: "Discord"
      url: "https://discord.gg/y6epv9R3"