baseURL: https://yoursite.example.com/
footnoteReturnLinkContents: ↩
params:
  AuthorName: Nexan
  GitHubUser: xanenightwing
  SidebarRecentLimit: 5
  Subtitle: Envoys of Dissonance
permalinks:
  posts: /:year/:month/:title/
title: Envoys of Dissonance
theme: "hugo-PaperMod"

params:
  profileMode:
    enabled: true
    title: "Envoys of Dissonance"
    subtitle: "Located on Aether DC, Gilgamesh"
    imageUrl: "<image Link>"
    imageTitle: "Envoys of Dissonance Logo"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: News
        url: "/news"
      - name: About
        url: "/page/about/"
  
  socialIcons:
    - name: "Discord"
      url: "https://discord.gg/y6epv9R3"

menu:
  main:
    - identifier: pages
      name: Pages
      url: /page/
      weight: 10
    - identifier: bfn #blank for now
      name: Blank
      url: https://nexxy.co
    #- identifier: posts
    #  name: Posts
    #  url: /posts/

# Front Matter config

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date